<a href="https://colab.research.google.com/github/Muhammad-Waleed-Source/Pandas/blob/main/Pandas_7_Vectorized_Strings_DateTime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

## Vectorized String Operations

In [4]:
# What are vectorized operations
a = np.array([1, 2, 3, 4])
a*4

array([ 4,  8, 12, 16])

In [5]:
# problem in vectoirzed operations in vanilla python
s = ['cat', 'mat', None, 'rat']

[i.startswith('c') for i in s] # this will give error because of None, we cannot apply startswith on None or missing data. So vanilla python is not able to handle it.

# Also this list comprehension is slow as time grows as number of list items grows

AttributeError: 'NoneType' object has no attribute 'startswith'

In [9]:
# How pandas solve this issue?
s = pd.Series(['cat', 'mat', None, 'rat'])

s.str.startswith('c') # str is string accessor

# fast and optimized

0     True
1    False
2     None
3    False
dtype: object

In [10]:
s.str.upper()

0     CAT
1     MAT
2    None
3     RAT
dtype: object

In [11]:
s.str.capitalize()

0     Cat
1     Mat
2    None
3     Rat
dtype: object

In [13]:
s.str.center(10)

0       cat
1       mat
2          None
3       rat
dtype: object